export const DISPONIVEL = "##7B8B99"
export const BORDADISP = "#C3CFD9"
export const SELECIONADO = "##0E7D71"
export const BORDASELEC = "#1AAE9E"
export const INDISPONIVEL = "##F7C52B"
export const BORDAINDISP = "#FBE192"